# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: ed69a6e51c1dcecc534ef14c6db9f4879867a2cc63f0552d9a5fc83bbd862ee59bf5d8491f145360ef72e0914e2cdb99f133f9fe65d0445c6a1711f7275f3b44

test:
  secret_key_base: fdceb938e8c68ebba7102177a47fe7600d3948cc9cda2d337bfe1d7dc9fbaa6cd3da16ad1ec6ee9a5c4098816778907588193746baa3c94d7bb70ce4cbb637de

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
